### ISSUE TITLE
Update MVI role and playbook documentation to incorporate object storage 

### ISSUE THREAD

**Issue by maulik-modi22** [ibm-mas/ansible-devops#1062]
MVI CR sample ‘spec’ section with Object Storage Enabled
```
spec: bindings:
edge: application settings:
imagePullPolicy: IfNotPresent 
storage:
  objectStorageBucketNames:
    workSpace: mvi-test-bucket-1
objectStorageEnabled: true
size: 100Gi
storageClassName: ibmc-file-gold
```
Additional settings in this release
```
objectStorageEnabled: true
objectStorageBucketNames:
  workSpace: mvi-test-bucket-1
```

https://ibm-mas.github.io/ansible-devops/playbooks/oneclick-visualinspection/

@dclain , @fyeh , @caroazad
