### ISSUE TITLE
mongodb task fails due to incorrect minor version number

### ISSUE THREAD

**Issue by JasonLKelly** [ibm-mas/ansible-devops#1157]
I'm trying to install MAS 8.11 using the `mas install` cli.
MongoDB 4.2.6
OCP on IBM Cloud

The mongodb task fails with this output:

```
TASK [ibm.mas_devops.mongodb : Set mongo_compatible_target_version] ************
fatal: [localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute '4.'. 'dict object' has no attribute '4.'
  
    The error appears to be in '/opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/mongodb/tasks/providers/community/check-mongo-exists.yml': line 56, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
        # mongo extras version are picked up from the catalog if available or uses defaults.
        - name: Set mongo_compatible_target_version
          ^ here
```

The problem appears earlier in the log: [frmas1-install-cbjsk-mongodb.log](https://github.com/ibm-mas/ansible-devops/files/13834470/frmas1-install-cbjsk-mongodb.log)

```
TASK [ibm.mas_devops.mongodb : Set existing_mongo_version] *********************
ok: [localhost] => changed=false 
  ansible_facts:
    existing_mongo_version: 4.2.6

TASK [ibm.mas_devops.mongodb : Set existing_mongo_minor_version] ***************
ok: [localhost] => changed=false 
  ansible_facts:
    existing_mongo_minor_version: '4.'
```

This appears to be the source:
https://github.com/ibm-mas/ansible-devops/blob/04a32fc3a4bc65e7bdaf1305b2bc6c6749f361be/ibm/mas_devops/roles/mongodb/tasks/providers/community/check-mongo-exists.yml#L39C83-L39C83

```
  # holds the existing mongo instance minor version
    - name: Set existing_mongo_minor_version
      set_fact:
        existing_mongo_minor_version: "{{ existing_mongo_version | regex_search('(?<=)(.*)(?=...)') }}"
```

This regex matches `4.` but should match `4.2`

**Comment by terenceq** [comment]
Given the fact that the devops collection will be controlling the versions something like this might be a better option:

```yaml
  - name: Set existing_mongo_minor_version
    set_fact:
      existing_mongo_minor_version: "{{ existing_mongo_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') }}"
```
