### ISSUE TITLE
db2_restore role fails during restore with "SQL2032N  The "DB2_CDE_REDUCED_LOGGING" parameter is not valid."

### ISSUE THREAD

**Issue by dirkhuppertz** [ibm-mas/ansible-devops#1162]
Hi all,
I tried to move the manage database from one MAS instance to an other MAS instance using the provided backup and restore roles.

Unfortunately, the restore task failed with the message: >SQL2032N  The "DB2_CDE_REDUCED_LOGGING" parameter is not valid. SQLSTATE=22531<.

```
TASK [ibm.mas_devops.db2_restore : Run restore.sh script (this can take several minutes...)] ********************************************************************************************************************
changed: [localhost] => changed=true
  cmd: oc exec -n db2u c-db2w-shared-db2u-0 -- su -lc '/tmp/restore.sh | tee /tmp/restore.log' db2inst1
  delta: '0:00:05.919665'
  end: '2024-01-08 16:20:26.670280'
  failed_when_result: false
  msg: ''
  rc: 0
  start: '2024-01-08 16:20:20.750615'
  stderr: 'Defaulted container "db2u" out of: db2u, init-labels (init), init-kernel (init)'
  stderr_lines: <omitted>
  stdout: |-
    SQL2032N  The "DB2_CDE_REDUCED_LOGGING" parameter is not valid.
    SQLSTATE=22531
  stdout_lines: <omitted>

TASK [ibm.mas_devops.db2_restore : debug] ***********************************************************************************************************************************************************************
ok: [localhost] =>
  msg:
  - 'SQL2032N  The "DB2_CDE_REDUCED_LOGGING" parameter is not valid.  '
  - SQLSTATE=22531
```

Here the used playbook:
```
- hosts: localhost
  any_errors_fatal: true
  vars:
    db2_namespace: "db2u"
    db2_dbname: "BLUDB"

    db2_restore_dir: "/playbooks/mno-06"
    db2_restore_instance_name: "db2w-shared"
  roles:
    - ibm.mas_devops.db2_restore
```

Any idea how to fix this??
