### ISSUE TITLE
WML PVCs have empty storage class name

### ISSUE THREAD

**Issue by SalaryTheft** [ibm-mas/ansible-devops#1180]
```bash
export CPD_PRIMARY_STORAGE_CLASS=nfs-client
export CPD_METADATA_STORAGE_CLASS=nfs-client
export CPD_SERVICE_STORAGE_CLASS=nfs-client

export CPD_INSTALL_PLATFORM="true"
...
export CPD_INSTALL_WML="true"
...
ansible-playbook ibm.mas_devops.oneclick_add_predict
```

I have found that WML etcd pods are not starting because of their volumes are not mounted.
It was happening due to `data-wml-cpd-etcd-x` PVCs have empty `spec: storageClassName`.
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-wml-cpd-etcd-0
  namespace: ibm-cpd
  ...
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ''
  volumeMode: Filesystem
```
