### ISSUE TITLE
Investigate use of blockedRegistries as alternative to /etc/host modifications

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#1201]
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/images/image-configuration

```yaml
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  name: cluster
spec:
  registrySources: 
    blockedRegistries:
    - quay.io
    - registry.redhat.io
    - icr.io
    - cp.icr.io
    - etc
```
