### ISSUE TITLE
Utilize ansible assert instead of fail / when

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#124]
Refer to: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/assert_module.html

Our roles would be better implemented like so:

```yaml
# 1. Check for required parameters
# -----------------------------------------------------------------------------
- name: "Assert that xxx is provided"
  assert:
    that:
      - xxx is defined
      - xxx != ""
    fail_msg: "xxx property is required"
```

instead of using the fail task guarded by a when.  This will result in clearer results as we won't have numerous skipped steps on success, instead the task will actually be marked as a success/failure.

When taking on this issue directly we should make this change globally; in addition all new code should follow this convention, and all updates to existing code should apply these changes as part of their work as a condition of acceptance.
