### ISSUE TITLE
Undefined variable: db2wh_svc_name in cp4d_db2wh

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#125]
```
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'db2wh_svc_name' is undefined\n\nThe error appears to be in '/opt/app-root/lib64/python3.8/site-packages/ansible_collections/ibm/mas_devops/roles/cp4d_db2wh/tasks/cpd35/provision-instance.yml': line 136, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# -----------------------------------------------------------------------------\n- name: \"Set service name and fqn from the instance ID\"\n ^ here\n"}
```

Easy fix ... we are assigning two facts at the same time, and seemingly can't reference the first one we assign in the latter ones:

```
- name: "Set service name and fqn from the instance ID"
  set_fact:
    db2wh_svc_name: "c-db2wh-{{ db2wh_instance_id }}-db2u-engn-svc"
    db2wh_svc_fqn: "{{ db2wh_svc_name }}.{{ db2wh_namespace }}.svc"
```

Should become:

```
- name: "Set service name and fqn from the instance ID"
  set_fact:
    db2wh_svc_name: "c-db2wh-{{ db2wh_instance_id }}-db2u-engn-svc"
    db2wh_svc_fqn: "c-db2wh-{{ db2wh_instance_id }}-db2u-engn-svc.{{ db2wh_namespace }}.svc"
```
