### ISSUE TITLE
Grafana dependencies not in ImageContentSourcePolicy

### ISSUE THREAD

**Issue by ChrisSchneiderIBM** [ibm-mas/ansible-devops#1264]
Hello,

the Grafana operator gets its dependencies from `ghcr.io/grafana` and `docker.io/grafana`

These are not in [redhat-catalogs.yml.j2](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/ocp_contentsourcepolicy/templates/redhat-catalogs.yml.j2) and thus the installation fails

For example I had to add the following entries to the generated ICSP:
```yaml
    - mirrors:
        - 'registry.gym.lan:8443/grafana'
      source: ghcr.io/grafana
    - mirrors:
        - 'registry.gym.lan:8443/grafana'
      source: docker.io/grafana
```
