### ISSUE TITLE
Role gencfg_jdbc generates file jdbc.yml. mas install does not work with that

### ISSUE THREAD

**Issue by ghost** [ibm-mas/ansible-devops#1267]
In mas install it is requiring a specific file name and extension. Even if you set the name right as expected, the extension .yml is also not recognized, so you have to change to .yaml instead.

So, the fix suggested here is to make the role result match with what mas install requires.

A plus would be to make mas install to accept both .yml and .yaml extensions.

**Comment by durera** [comment]
Looks like this was fixed at some point in the past year, but wasn't linked back to this issue - in the code I can see that the`suite_config` role is looking for both .yaml and .yml files to apply.

```yaml
# 3. Apply optional MAS configuration
# -----------------------------------------------------------------------------
- name: Find *.yml and *.yaml files in the MAS config directory
  find:
    paths: "{{ mas_config_dir }}"
    patterns: '*.yml,*.yaml'
    recurse: no
  register: mas_config_files
```
