### ISSUE TITLE
Integrate must-gather role into tekton pipeline

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#131]
Refer to https://developer.ibm.com/blogs/add-finally-to-tekton-pipelines/ for more information.  The basic premise is that after the pipeline completes (successfully or otherwise) we should execute the mustgather role, collect the file, and somehow make it available to the user to download to their local system once the pipeline run has completed.

ie. something like this needs to be added to the pipeline spec to run the must-gather, and then we need a way to access the generated file and make it available to the user to access:
```yaml
spec:
  status: StoppedRunFinally
  finally:
    - name: must-gather
      params:
        - name: junit_suite_name
          value: must-gather
      taskRef:
        kind: ClusterTask
        name: mas-devops-must-gather
      workspaces:
        - name: settings
          workspace: shared-settings
```

This will prove invaluable in debugging user executions, and failures in our own FVT pipeline
