### ISSUE TITLE
CASE bundle has different common services operator version than defaultChannel

### ISSUE THREAD

**Issue by ChrisSchneiderIBM** [ibm-mas/ansible-devops#1365]
Hello,

the CASE bundle for `v9-240625-amd64` references `common_svcs_version: 4.3.0`:
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/common_vars/casebundles/v9-240625-amd64.yml

However, the PackageManifest lists `defaultChannel: v3.23`:
```yml
kind: PackageManifest
apiVersion: packages.operators.coreos.com/v1
metadata:
  name: ibm-common-service-operator
  namespace: openshift-marketplace
...
spec:
...
  defaultChannel: v3.23
```

In air-gapped situations this leads to the following scenario:
* Common Service Operator v4.3.0 is mirrored
* The Ansible script installs Common Service Operator v3.23
* This leads to an image not found error and the installation stops
* A possible workaround is to specify `COMMON_SERVICES_CHANNEL`, but this needs to be matched to each new CASE bundle
