### ISSUE TITLE
Error with Manage attachments (suite_manage_attachments_config role)

### ISSUE THREAD

**Issue by SalaryTheft** [ibm-mas/ansible-devops#1437]
### Collection version

18.17.2

### Environment information

```console
Python 3.12.1
Ansible 2.12
```

### What happened?

A few months ago, I deployed Maximo Manage 8.7.6 in a customer environment and set up attachments(doclinks) using `suite_manage_attachments_config` role with `MAS_MANAGE_ATTACHMENT_CONFIGURATION_MODE` set to `cr`.  

I recently discovered that attchements are not working and getting following error in the server log:
```
28 Aug 2024 00:54:55:091 [ERROR] [MXServer] [CID-MXOSLC-20321] null
java.lang.ClassNotFoundException: null
	at java.lang.Class.forNameImpl(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:347) ~[?:?]
	at com.ibm.tivoli.maximo.oslc.provider.AttachmentStorage.getInstance(AttachmentStorage.java:69) [businessobjects.jar:?]
```

In ManageWorkspace CR, `mxe.attachmentstorage` is set to literal string `null` in server bundle properties.
```yaml
spec:
    deployment:
      serverBundles:
        - bundleLevelProperties: |-
            mxe.doclink.doctypes.topLevelPaths=/DOCLINKS
            mxe.doclink.doctypes.defpath=/DOCLINKS/default
            mxe.doclink.path01=/DOCLINKS=https://dev.manage.ocp.company.com/maximo/oslc/doclinks
            mxe.doclink.securedAttachment=true
            mxe.report.AttachDoc.validateURL=0
            mxe.attachmentstorage=null
```

I believe it is defined at following function and havent changed from the version I've used for deployment. (18.17.2)
https://github.com/ibm-mas/ansible-devops/blob/597805f28eb305617f6693ce30f71285c03d8c95/ibm/mas_devops/plugins/filter/filters.py#L348

### Relevant log output

```shell
// Logs are provided above
```

**Comment by faangbait** [comment]
I suspect you're missing some variables. Here's how we do it:

```
    - name: Configure Manage Attachment Storage
      include_role: 
        name: ibm.mas_devops.suite_manage_attachments_config
      vars:
        mas_instance_id: "max"
        mas_workspace_id: "{{ workspace_id | default('masdev') | lower }}"
        mas_manage_attachments_provider: aws
        mas_manage_attachment_configuration_mode: cr
        aws_bucket_name: "{{ cluster_name }}-{{ workspace_id | default('masdev') | lower }}-attachments"
        aws_region: us-east-2
        aws_access_point_region: us-east-2
```
