### ISSUE TITLE
mirroring does not include some of the Grafana images

### ISSUE THREAD

**Issue by witekwww** [ibm-mas/ansible-devops#1457]
### Collection version

22.5.2

### Environment information

```console
quay.io/ibmmas/cli 10.9.2
```

### What happened?

Mirroring of OpenShift catalogs does not include some of the Grafana images. Image for Operator deployment is there, but i'm missing image for mas-grafana-deployment (docker.io/grafana/grafana:10.4.3)

### Relevant log output

```shell
status of pod:

status:
  phase: Pending
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-09-06T13:02:19Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2024-09-06T13:02:19Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [grafana]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2024-09-06T13:02:19Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [grafana]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-09-06T13:02:19Z'
  hostIP: 192.168.222.210
  podIP: 10.128.0.248
  podIPs:
    - ip: 10.128.0.248
  startTime: '2024-09-06T13:02:19Z'
  containerStatuses:
    - name: grafana
      state:
        waiting:
          reason: ImagePullBackOff
          message: 'Back-off pulling image "docker.io/grafana/grafana:10.4.3"'
      lastState: {}
      ready: false
      restartCount: 0
      image: 'docker.io/grafana/grafana:10.4.3'
      imageID: ''
      started: false
```

**Comment by durera** [comment]
Unfortunately the issues with older releases of the Grafana operator's (lack of) support for airgap are not something we can address.

Thankfully newer releases do support disconnected install:

We can see this on our test systems: 

`grafana-operator-controller-manager-v5-b98ccfddc-l2pgb`:
```yaml
  spec:
    containers:
    - args:
      - --health-probe-bind-address=:8081
      - --metrics-bind-address=0.0.0.0:9090
      - --leader-elect
      env:
      - name: RELATED_IMAGE_GRAFANA
        value: docker.io/grafana/grafana@sha256:a0f881232a6fb71a0554a47d0fe2203b6888fe77f4cefb7ea62bed7eb54e13c3
      - name: WATCH_NAMESPACE
      - name: DASHBOARD_NAMESPACES_ALL
        value: "true"
      - name: OPERATOR_CONDITION_NAME
        value: grafana-operator.v5.16.0
      image: ghcr.io/grafana/grafana-operator@sha256:8319c1a947d8fa79379d895527e279ce121db3b3589232af088dde7d7d499740
```

`mas-grafana-deployment-64b7b4699c-7zswn`
```
  spec:
    containers:
    - args:
      - -config=/etc/grafana/grafana.ini
      env:
      - name: PLUGINS_HASH
        valueFrom:
          configMapKeyRef:
            key: PLUGINS_HASH
            name: mas-grafana-plugins
            optional: true
      - name: CONFIG_HASH
        value: 469e4e3b186ea60b355efea7392957952b755e29038e5122e41f6be20379fa39
      - name: GF_INSTALL_PLUGINS
      - name: TMPDIR
        value: /var/lib/grafana
      - name: GF_SECURITY_ADMIN_USER
        valueFrom:
          secretKeyRef:
            key: GF_SECURITY_ADMIN_USER
            name: mas-grafana-admin-credentials
      - name: GF_SECURITY_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            key: GF_SECURITY_ADMIN_PASSWORD
            name: mas-grafana-admin-credentials
      image: docker.io/grafana/grafana@sha256:a0f881232a6fb71a0554a47d0fe2203b6888fe77f4cefb7ea62bed7eb54e13c3
```

The version of grafana used on your cluster is determined by the version of the Red Hat Catalog that you have mirrored, if you chose a recent version of the Red Hat Community Operator Catalog then you will find that Grafana now correctly functions in a disconnected environment.
