### ISSUE TITLE
Failure during CP4D install role, unable to retrieve status from zenmetastore EDB cluster

### ISSUE THREAD

**Issue by rene-oromtz** [ibm-mas/ansible-devops#1612]
### Collection version

25.0.1 

### Environment information

```console
quay.io/ibmmas/cli:12.1.0
```

### What happened?

While installing Predict via mas install, the CP4D role is getting stalled at:
`TASK [ibm.mas_devops.cp4d : install-cp4d : Wait for zen-metadata to be ready again (60s delay)]`

The problem seems to be related to the fact that there are two different "Cluster" kind defined in the cluster
```
oc api-resources|egrep -w "clusters|NAME"
NAME                                  SHORTNAMES                                                                             APIVERSION                                                 NAMESPACED   KIND
clusters                                                                                                                     application.isf.ibm.com/v1                                 true         Cluster
clusters                                                                                                                     postgresql.k8s.enterprisedb.io/v1                          true         Cluster
```

### Relevant log output

From /opt/app-root/lib64/python3.9/site-packages/ansible_collections/ibm/mas_devops/roles/cp4d/tasks/wait/wait-zenmetastore-edb.yml

This task is waiting for zen megastore cluster to start:

```
# 1. Wait for zen metastore cluster to start
# -----------------------------------------------------------------------------
- name: "wait-zenmetastore-edb : Wait for Zen Metastore EDB Cluster to be created"
  k8s_info:
    kind: Cluster
    namespace: "{{ cpd_instance_namespace }}"
    name: "zen-metastore-edb"
  register: zenmetastoreCluster
  retries: 120 # Give 60 minutes for the zenService to start Zen Metastore Pods (Logs show this taking ~20 minutes in a good run)
  delay: 30
  until: zenmetastoreCluster.resources[0].status is defined
```

This task is missing the apiversion related to edb Postgres:

Task should be defined as:
```
k8s_info:
    api_version: postgresql.k8s.enterprisedb.io/v1
    kind: Cluster
    namespace: "{{ cpd_instance_namespace }}"
    name: "zen-metastore-edb"
```

The role is getting stalled at verification:
```
FAILED - RETRYING: [localhost]: wait-zenmetastore-edb : Wait for Zen Metastore EDB Cluster to be created (52 retries left).
FAILED - RETRYING: [localhost]: wait-zenmetastore-edb : Wait for Zen Metastore EDB Cluster to be created (51 retries left).
FAILED - RETRYING: [localhost]: wait-zenmetastore-edb : Wait for Zen Metastore EDB Cluster to be created (50 retries left).
FAILED - RETRYING: [localhost]: wait-zenmetastore-edb : Wait for Zen Metastore EDB Cluster to be created (49 retries left).
...

fatal: [localhost]: FAILED! => changed=false 
  api_found: false
  attempts: 120
  msg: Failed to find API for resource with apiVersion "v1" and kind "Cluster"
  resources: []
```
Looking at the "Cluster" CR via CLI is identifying the one with apiversion:application.isf.ibm.com/v1 so this is why is getting stuck at this step

```
oc get cluster -A
NAMESPACE                NAME                        AGE
ibm-spectrum-fusion-ns   apps.rackm15.mydomain.com   74d
```

As verification, zenmetastore cluster is already healthy:

```
oc get cluster.postgresql.k8s.enterprisedb.io -n ibm-cpd
NAME                AGE   INSTANCES   READY   STATUS                     PRIMARY
zen-metastore-edb   40m   2           2       Cluster in healthy state   zen-metastore-edb-1
```
