### ISSUE TITLE
Support module_defaults for Kubernetes server connection

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#1653]
### Collection version

26.1.1

### Environment information

```console
ansible --version
ansible [core 2.15.13]
  config file = /home/david/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/david/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/david/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/david/.local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### What happened?

In our [actions](https://github.com/ibm-mas/ansible-devops/blob/b50817f8f65f55c038d41ec73515bbf577babe83/ibm/mas_devops/plugins/action/get_default_storage_classes.py#L27) we connect to Kubernetes using the k8s module:

```python
from ansible_collections.kubernetes.core.plugins.module_utils.k8s.client import get_api_client

dynClient = get_api_client()
```

This calls the k8s module's [get_api_client() method](https://github.com/ansible-collections/kubernetes.core/blob/91df2f10bc254633a8892118da0ce589703ec514/plugins/module_utils/k8s/client.py#L338)

This works how we normally use the collection:

```bash
oc login --token xxx --server xxx
ansible-playbook ibm.mas_devops.whatever
```

However, customer has reported that they have been using [module defaults](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_module_defaults.html), which has worked previously because **most** but not all of our kubernetes interactions are via the k8s module:

```
module_defaults:
  group/kubernetes.core.k8s:
    host: "{{ ocp_auth_api }}"
    api_key: "{{ vault_ocp_jenkins_sa_token }}"
```

Now that we have our own module, this isn't working.  The objective here is to support a way that either these existing defaults somehow work when you use our modules, or we provide similar support for a `group/ibm.mas_devops` (or whatever) so that you can at least define similar defaults for our module too, such that you can do something like:

```yaml
---
- hosts: localhost
  any_errors_fatal: true

  module_defaults:
    group/kubernetes.core.k8s:
      host: "https://xxxx"
      api_key: "sha256~xxxxx"

  tasks:
    - name: "Lookup default storage classes"
      ibm.mas_devops.get_default_storage_classes:
      register: defaultStorageClasses
```

This should allow us to return the default supported storage classes on a server without having to first `oc login` to the server, and without modifying the default context in `KUBECONFIG` file (potentially having to add our own module_defaults, but ideally re-using the module defaults from the kuberentes.core.k8s group).

### Relevant log output

```shell
N/A
```
