### ISSUE TITLE
Make the MongoDb install AirGap friendly

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#173]
Issue raised internally by Rick Acree, transferring to here for better tracking/visibility.  

MongoDB needs to be deployed using image@digest for it to work in AirGap cluster

manager.yml should specify entries such as 

       - name: AGENT_IMAGE
          value: quay.io/mongodb/mongodb-agent@sha256:a6b316e6df0fee2c3d64cb065260e33586330784dcaab02cc7a3052cde3c94b9
        - name: VERSION_UPGRADE_HOOK_IMAGE
          value: quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook@sha256:da347eb74525715a670280545e78ecee1195ec2630037b3821591c87f7a314ee
        - name: READINESS_PROBE_IMAGE
          value: quay.io/mongodb/mongodb-kubernetes-readinessprobe@sha256:bf5a4ffc8d2d257d6d9eb45d3e521f30b2e049a9b60ddc8e4865448e035502ca
        image: quay.io/mongodb/mongodb-kubernetes-operator@sha256:e19ae43539521f0350fb71684757dc535fc989deb75f3789cd84b782489eda80

cr.yml should specify "image:" in the statefulSet

```
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              image: quay.io/ibmmas/mongo@sha256:8c48baa1571469d7f5ae6d603b92b8027ada5eb39826c009cb33a13b46864908
````
