### ISSUE TITLE
Extend ansible support to enable WSL/WML to be configured in MAS #261

### ISSUE THREAD

**Issue by andrercm** [ibm-mas/ansible-devops#192]
- Need to filling the blanks for Watson Studio configuration for MAS. So this code in ansible needs to create the WatsonStudioCfg. 
- Minimally this CR needs to include something as the example below:

```
apiVersion: config.mas.ibm.com/v1
kind: WatsonStudioCfg
metadata:
  name: mas87upgrade-watsonstudio-system
  namespace: mas-mas87upgrade-core
  labels:
    mas.ibm.com/configScope: system
    mas.ibm.com/instanceId: mas87upgrade
spec:
  config:
    credentials:
      secretName: mas87upgrade-usersupplied-watsonstudio-creds-system
    endpoint: >-
      https://cpd-meta-ops-cpd-cpd-meta-ops.ivt87upgrade-6f1620198115433da1cac8216c06779b-0000.eu-gb.containers.appdomain.cloud
  displayName: >-
    https://cpd-meta-ops-cpd-cpd-meta-ops.ivt87upgrade-6f1620198115433da1cac8216c06779b-0000.eu-gb.containers.appdomain.cloud
  type: external
```

The CR above will also need a secret to store CPD user/pass:
```
kind: Secret
apiVersion: v1
metadata:
  name: mas87upgrade-usersupplied-watsonstudio-creds-system
  namespace: mas-mas87upgrade-core
 data:
  password: cGFzc3dvcmQ=
  username: YWRtaW4=
type: Opaque
```
