### ISSUE TITLE
Add MSO as a Dependency to Manage & Health to enable AIO

### ISSUE THREAD

**Issue by lokesh-sreedhara** [ibm-mas/ansible-devops#264]
Would like to add a new dependency for Health on FVT , health-aio component requires MSO. So we will need to install MSO Before Health and set install AIO (Asset Investment Optimization)  to `true` on the Health/Manage Workspace CR
```
spec:
 settings:
    aio:
      install: true
```
