### ISSUE TITLE
[Bugs]segmentKey shows the omit_place_holder instead of omitted in role gencfg_uds 

### ISSUE THREAD

**Issue by Yolandabjyf** [ibm-mas/ansible-devops#277]
I run the playbook of gencfg_uds  and it create the uds.yml successfully. But the segmentKey looks wrong.
It should remove the whole entry for segmentKey rather than have the omit_place_holder when I don’t set it.
The uds.yml generated by the role like this:
```
spec:
  displayName: UDS sre-yld-test
  config:
    url: "https://uds-endpoint-ibm-common-services.apps.sre-saas-dev01.pkl7.p1.openshiftapps.com/"
    contact:
      email: "MAS.Production@uk.ibm.com"
      firstName: "MAS"
      lastName: "Production"
    credentials:
      secretName: uds-apikey
    segmentKey: "__omit_place_holder__f14760e42e8108bec69dd68c54772a6d84646450"
  certificates:
    - alias: part1
```
