### ISSUE TITLE
db2 role needs the no_root_squash + remove cp4d settings from spec

### ISSUE THREAD

**Issue by whitfiea** [ibm-mas/ansible-devops#311]
The db2 role has been changed to use file storage for some of it storage. When using IBM ROKS this means you get NFS based storage and so we need to setup the no_root_squash daemonset https://www.ibm.com/docs/en/cloud-paks/cp-data/3.0.1?topic=nsr-configuring-nfs-cloud-file-storage-gold-storage-class in order for the db2u pod to work.

We also need to remove the following from the db2ucluster cr spec as these are cp4d specific settings:

```
  advOpts:
    db2SecurityPlugin: cloud_gss_plugin

      dbmConfig:
        SRVCON_PW_PLUGIN: IBMIAMauthpwfile
        group_plugin: IBMIAMauthgroup
        srvcon_auth: GSS_SERVER_ENCRYPT
        srvcon_gssplugin_list: IBMIAMauth
```
