### ISSUE TITLE
custom mas_app_ws_spec is not working 

### ISSUE THREAD

**Issue by belfortmaycon** [ibm-mas/ansible-devops#334]
I'm trying to export the variable mas_app_ws_spec with custom specs for Manage deployment and it is always using the default specs.

Custom specs
```yaml
bindings:
    jdbc: system
  components:
    base:
      version: latest
    transportation:
      version: latest
  settings:
    db:
      maxinst:
        bypassUpgradeVersionCheck: false
        db2Vargraphic: true
        demodata: true
        indexSpace: MAXINDEX
        tableSpace: MAXDATA
      dbSchema: maximo
    languages:
      baseLang: PT-BR
      secondaryLangs:
        - EN
    deployment:
      serverBundles:
        - bundleType: ui
          isDefault: true
          isUserSyncTarget: false
          name: ui
          replica: 1
          routeSubDomain: all
          isMobileTarget: true
        - name: cron
          replica: 1
          bundleType: cron
          routeSubDomain: bundle1
          isUserSyncTarget: false
          isDefault: false
          isMobileTarget: false
        - name: mea
          replica: 1
          bundleType: mea
          routeSubDomain: bundle2
          isUserSyncTarget: true
          isDefault: false
          isMobileTarget: false
        - name: report
          replica: 1
          bundleType: report
          routeSubDomain: bundle3
          isDefault: false
          isMobileTarget: false
          isUserSyncTarget: false
      serverTimezone: Brazil/East
```

Variable export:
```shell
export MAS_APP_WS_SPEC=~/activate-manage-details.yaml
```

Output:
```shell
TASK [ibm.mas_devops.suite_app_config : Load default application workspace spec] ********************************************************************************************************************************************
Thursday 09 June 2022  19:52:13 +0000 (0:00:00.096)       0:00:01.700 ********* 
ok: [localhost] => {"ansible_facts": {"mas_app_ws_spec": {"bindings": {"jdbc": "{{ mas_appws_jdbc_binding | default( 'system' , true) }}"}, "components": "{{ mas_appws_components | default({'base':{'version':'latest'}}, true) }}", "settings": {"aio": {"install": true}, "db": {"dbSchema": "{{ db2_schema }}", "maxinst": {"bypassUpgradeVersionCheck": false, "db2Vargraphic": true, "demodata": "{{ manage_demo_data | bool }}", "indexSpace": "MAXINDEX", "tableSpace": "MAXDATA"}}}}}, "ansible_included_var_files": ["/opt/app-root/lib64/python3.8/site-packages/ansible_collections/ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/manage.yml"], "changed": false}
```

**Comment by whitfiea** [comment]
@belfortmaycon There is no environment variable support for `mas_app_ws_spec` you most set this as a var in your playbook. See https://ibm-mas.github.io/ansible-devops/roles/suite_app_config/#mas_app_ws_spec and the example playbook below it.

**Comment by belfortmaycon** [comment]
@whitfiea I got it. And how do I run this new playbook that I will create? Where should I save the playbook?

**Comment by whitfiea** [comment]
@belfortmaycon How/What are you currently running to run the suite_app_config role at the moment? You can take an existing playbook like https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/playbooks/oneclick_add_manage.yml and either add the `mas_app_ws_spec` var to it or create your own playbook that runs the roles you need and has the var. For your own playbook you can save it locally and then just run `ansible-playbook my_playbook.yaml`

**Comment by belfortmaycon** [comment]
@whitfiea I'm using the docker image to run the playbook. I'm exporting the variables and then run the `run_role`.

```bash
export [...]
export ROLE_NAME=suite_app_config

ansible-playbook ibm.mas_devops.run_role
```

**Comment by whitfiea** [comment]
@belfortmaycon ok then you can make a new playbook (call it my_playbook.yaml forexample) within the docker image that looks like this:
```
- hosts: localhost
  any_errors_fatal: true
  vars:
    mas_app_ws_spec:
       <the contents of your activate-manage-details.yaml file>

  roles:
    - ibm.mas_devops.suite_app_config
```

then just run it `ansible-playbook my_playbook.yaml`

**Comment by belfortmaycon** [comment]
I was able to create my own playbook and run it. However, when setting the `MAS_CONFIG_SCOPE` to `wsapp` it is always generating the system `jdbc.yaml` template.

```bash
TASK [ibm.mas_devops.db2 : include_tasks] ****************************************************************************************
Sunday 12 June 2022  00:02:27 +0000 (0:00:03.691)       0:05:49.711 *********** 
included: /opt/app-root/lib64/python3.8/site-packages/ansible_collections/ibm/mas_devops/roles/db2/tasks/suite_jdbccfg.yml for localhost

TASK [ibm.mas_devops.db2 : Load variables to use in JDBCCfg] *********************************************************************
Sunday 12 June 2022  00:02:27 +0000 (0:00:00.088)       0:05:49.800 *********** 
ok: [localhost] => {"ansible_facts": {"suite_jdbccfg_labels": {"mas.ibm.com/applicationId": "{{ mas_application_id }}", "mas.ibm.com/configScope": "workspace-application", "mas.ibm.com/instanceId": "{{ mas_instance_id }}", "mas.ibm.com/workspaceId": "{{ mas_workspace_id }}"}, "suite_jdbccfg_name": "{{ mas_instance_id }}-jdbc-wsapp-{{mas_workspace_id}}-{{mas_application_id}}"}, "ansible_included_var_files": ["/opt/app-root/lib64/python3.8/site-packages/ansible_collections/ibm/mas_devops/roles/db2/vars/jdbccfg/wsapp.yml"], "changed": false}
```
```bash
TASK [ibm.mas_devops.db2 : Copy JdbcCfg to filesytem] ****************************************************************************
Sunday 12 June 2022  00:02:29 +0000 (0:00:00.089)       0:05:52.111 *********** 
changed: [localhost] => {"changed": true, "checksum": "64e497e7ccbd042dcd415cc23d10e46f621a592e", "dest": "/opt/app-root/src/masconfigtest/jdbc-masdev2-db2u.yml", "gid": 0, "group": "root", "md5sum": "16e07dfc8dd62700694ed3886b5f24df", "mode": "0644", "owner": "root", "size": 2180, "src": "/root/.ansible/tmp/ansible-tmp-1654992149.9627867-6930-214048180065464/source", "state": "file", "uid": 0}
```

```yaml
---
apiVersion: config.mas.ibm.com/v1
kind: JdbcCfg
metadata:
  name: "dev-jdbc-system"
  namespace: "mas-dev-core"
  labels:
    mas.ibm.com/configScope: system
    mas.ibm.com/instanceId: "dev"
spec:
  displayName: "masdev2 on CP4D"
  config:
    url: "jdbc:db2://c-masdev2-db2u-engn-svc.db2u.svc:50001/BLUDB:sslConnection=true;"
    sslEnabled: true
    credentials:
      secretName: "jdbc-masdev2-credentials"
  certificates:
    - alias: "masdev2"
      crt: |
```

Test:
```bash
export MAS_INSTANCE_ID=dev
export MAS_CONFIG_DIR=~/masconfigdev
export DB2_INSTANCE_NAME=masdev2
export ENTITLEMENT_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWFya2V0cGxhY2UiLCJpYXQiOjE2NTA2NDg4NTUsImp0aSI6ImMzMjA1MmM2N2JmODQ3NTJiMTEwNTM4Yjg4MjQ2NDQ2In0.56ZJnYyK-wMZ_Q0w2_AdZlp7Ly5dOC9imHZI6M8tRYE
export MAS_CONFIG_SCOPE=wsapp
export MAS_WORKSPACE_ID=mas
export MAS_APP_ID=manage
export DB2_DBNAME=BLUDB
export ROLE_NAME=db2

ansible-playbook ibm.mas_devops.run_role
```
