### ISSUE TITLE
Automatically configure storage classes in ROSA

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#361]
Out of the box ROSA only comes with a `RWO` storage class (backed by EBS), additional steps are required to set up the `RWX` storage class (based by EFS).  We need to automate these steps in a new role `ibm.mas_devops.ocp_efs`

The ROSA provision playbook should include this new role so that the newly provisioned cluster is set up fully ready to use for MAS:

e.g.

```yaml
roles:
  roles:
    # 1. Provision the ROSA cluster
    - ibm.mas_devops.ocp_provision

    # 2. Login and verify the cluster is ready
    - ibm.mas_devops.ocp_login
    - ibm.mas_devops.ocp_verify

    # 3. Set up storage classes
    - ibm.mas_devops.ocp_efs
```

Refer to the following docs for help, this is the process we need to automate in the new role:
- https://docs.openshift.com/rosa/storage/persistent_storage/osd-persistent-storage-aws.html
