### ISSUE TITLE
Timing window in mongodb role when waiting for sts

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#363]
The condition should also check for the existence of resources, otherwise there is a window where the task can blow up:
```
"msg": "The conditional check 'mongodb_statefulset.resources | length > 0' failed. The error was: error while evaluating conditional (mongodb_statefulset.resources | length > 0): 'dict object' has no attribute 'resources'"
```

```
# 9. Wait for the cluster to be ready
# -----------------------------------------------------------------------------
- name: "mongodb/community : Wait for stateful set to be ready"
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: StatefulSet
    name: mas-mongo-ce
    namespace: "{{ mongodb_namespace }}"
  register: mongodb_statefulset
  retries: 60 # 30 * 30 seconds = 15 minutes
  delay: 30
  until:
    - mongodb_statefulset.resources | length > 0
    - mongodb_statefulset.resources[0].status.readyReplicas is defined
    - mongodb_statefulset.resources[0].status.readyReplicas == 3
```

Observing the cluster everything is fine, we just need the code to be a little more resiliant:

```
david@IBM-PF36VLBJ:~/maximoappsuite/dashboard/image/dashboard/src$ oc -n mongoce get sts
NAME           READY   AGE
mas-mongo-ce   2/3     42m
david@IBM-PF36VLBJ:~/maximoappsuite/dashboard/image/dashboard/src$ oc -n mongoce get pods
NAME                                           READY   STATUS    RESTARTS   AGE
mas-mongo-ce-0                                 2/2     Running   0          42m
mas-mongo-ce-1                                 2/2     Running   0          38m
mas-mongo-ce-2                                 0/2     Pending   0          36m
mongodb-kubernetes-operator-6bfb948c5c-smqzd   1/1     Running   0          42m
```
