### ISSUE TITLE
IBM MAS DB2 schedule backups

### ISSUE THREAD

**Issue by belfortmaycon** [ibm-mas/ansible-devops#414]
Hi Team,

I'm trying to configure the role db2_backup to run in a Cronjob of RHOS but I'm worried about how can run this role with a custom playbook on param command, should I create my own image? Is there a way to use the ibm-mas image?

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: db2BackupCronJob
spec:
  schedule: "*/1 * * * *"  
  concurrencyPolicy: "Replace" 
  startingDeadlineSeconds: 200 
  suspend: true            
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 1     
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cronjob"
        spec:
          containers:
          - name: 
            image: quay.io/ibmmas/ansible-devops:latest
            command: ["ansible-playbook",  "?????????"]
          restartPolicy: OnFailure 
```

**Comment by durera** [comment]
You're most of the way there ... something like this would work:

```
        spec:
          containers:
          - name: 
            image: quay.io/ibmmas/ansible-devops:latest
            env:
              - name: ROLE_NAME
                value: db2_backup
              - name: DB2_BACKUP_DIR
                value: xxx
              - name: DB2_BACKUP_INSTANCE_NAME
                value: xxx
              - name: DB2_NAMESPACE
                value: xxx
            command: ["ansible-playbook",  "ibm.mas_devops.run_role"]
```

The `run_role` playbook will execute the role defined by `ROLE_NAME`, and is a nice shorthand for running any role in the collection standalone using ansible-playbook.
