### ISSUE TITLE
Wrong configuration file when Mongo replicas is not 3

### ISSUE THREAD

**Issue by evilADevil** [ibm-mas/ansible-devops#480]
Using `ibm.mas_devops.mongodb` with `mongodb_replicas: 1` creates a wrong MAS config (`mongo-mongoce.yml`) that references 3 instances:
```
...
spec:
  displayName: "MongoDb 4.2.6 Community Edition in 'mongoce' namespace"
  type: external
  config:
    hosts:
      - host: "mas-mongo-ce-0.mas-mongo-ce-svc.mongoce.svc.cluster.local"
        port: 27017
      - host: "mas-mongo-ce-1.mas-mongo-ce-svc.mongoce.svc.cluster.local"
        port: 27017
      - host: "mas-mongo-ce-2.mas-mongo-ce-svc.mongoce.svc.cluster.local"
        port: 27017
    configDb: admin
    authMechanism: DEFAULT
...
```
