### ISSUE TITLE
regex used in udscfg task causes deprecation warning - error with Python 3.11

### ISSUE THREAD

**Issue by terenceq** [ibm-mas/ansible-devops#564]
## regex pattern used in udscfg task results in deprecation warning

The offending regex is here:

https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/uds/tasks/install/udscfg.yml#L64

```yaml
- name: "udscfg : Set UDS cert variable"
  set_fact:
    uds_tls_crt: "{{ cluster_ingress_tls_crt | regex_findall('(-----BEGIN .+?-----(?s).+?-----END .+?-----)', multiline=True, ignorecase=True) }}"

```

The `regex_findall` task is a built in task that is a Python filter. So this probably results in something like:

```python
cert_pattern = r'(-----BEGIN .+?-----(?s).+?-----END .+?-----)'
results = re.findall(cert_pattern, decoded_certs, re.MULTILINE|re.IGNORECASE )
```

And this gives the following deprecation warning:

> DeprecationWarning: Flags not at the start of the expression '(-----BEGIN .+?-----' (truncated)

And in Python 3.11 it is an error and causes the `udscfg` task to fail.

### Proposed fix

Since the precedence in the regex is already set to [match newlines with the (?s) flag](https://docs.python.org/3/library/re.html#re.DOTALL) in the `END` section of pattern - simply move the global flag to the beginning of the pattern:

```python
cert_pattern = r'(?s)(-----BEGIN .+?-----.+?-----END .+?-----)'
results = re.findall(cert_pattern, decoded_certs, re.MULTILINE|re.IGNORECASE )
```
