### ISSUE TITLE
Why is there no workload size param for Monitor?

### ISSUE THREAD

**Issue by aroute** [ibm-mas/ansible-devops#586]
IoT has `MAS_APP_SETTINGS_IOT_DEPLOYMENT_SIZE` but there is nothing available to set workload size of dev for Monitor.

**Comment by andrercm** [comment]
This seems a quick winner, we can leverage that into multiple places, will include it in the plan for the upcoming enhancements in our backlog.

Just like we do here for iot, we'd do same for monitor:

IoT:
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_app_install/vars/defaultspecs/iot.yml#L8

Monitor:
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_app_install/vars/defaultspecs/monitor.yml

Here's a sample of how MonitorApp CR spec should look like:
```
spec:
  bindings:
    jdbc: system
    kafka: system
    mongo: system
  components: {}
  settings:
    deployment:
      size: small
```
