### ISSUE TITLE
oneclick_add_predict yaml formatting causes install  failure

### ISSUE THREAD

**Issue by ekambaraml** [ibm-mas/ansible-devops#744]
command:
ansible-playbook ibm.mas_devops.oneclick_add_predict

Error:

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/26153008/228927738-3f374aa7-6f63-4e73-9738-89d2c9a3cd2f.png">

Fix 

modify the file https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/playbooks/oneclick_add_predict.yml to add two spaces to add indentation.

```yaml
    - include_role:
      name: ibm.mas_devops.cp4d_service
      when: install_spss_modeler == true
      vars:
        cpd_service_name: spss

  After the fix:

    - include_role:
        name: ibm.mas_devops.cp4d_service
      when: install_spss_modeler == true
      vars:
        cpd_service_name: spss
```
