### ISSUE TITLE
When running suite_app_config to activate manage, persistent volume is duplicate

### ISSUE THREAD

**Issue by andrercm** [ibm-mas/ansible-devops#746]
After running twice the `suite_app_config` the persistent volume gets duplicated as below:

```
persistentVolumes:
        - mountPath: /DOCLINKS
          pvcName: manage-doclinks
          size: 20Gi
          storageClassName: ibmc-file-gold-gid
        - mountPath: /bim
          pvcName: manage-bim
          size: 20Gi
          storageClassName: ibmc-file-gold-gid
        - mountPath: /jms
          pvcName: manage-jms
          size: 20Gi
          storageClassName: ibmc-file-gold-gid
        - mountPath: /DOCLINKS
          pvcName: manage-doclinks
          size: 20Gi
          storageClassName: ibmc-file-gold-gid
        - mountPath: /bim
          pvcName: manage-bim
          size: 20Gi
          storageClassName: ibmc-file-gold-gid
        - mountPath: /jms
          pvcName: manage-jms
          size: 20Gi
          storageClassName: ibmc-file-gold-gid
```
