### ISSUE TITLE
Consistent behaviour: BAS role should check for mas_config_dir being set

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#77]
Other roles, have a conditional check for MAS_CONFIG_DIR, they only save the file when it's set, for example in db2 (same logic can be see in kafka and mongo dep roles):

```
# 3. Generate a JdbcCfg for MAS configuration
# -----------------------------------------------------------------------------
- include_tasks: tasks/suite_jdbccfg.yml
  when:
    - mas_instance_id is defined
    - mas_instance_id != ""
    - mas_config_dir is defined
    - mas_config_dir != ""
```

However in BAS, we don't seem to have any check for whether config dir has been set, resulting in potentially writing to a dangerous and/or undesirable directory if mas_config_dir == "" (which it will if the env var was not set).

```
- name: Set facts for BASCfg
  set_fact:
    bas_segment_key: "{{_bas_segmentKey_result.resources[0].data.segmentkey | b64decode}}"
    bas_api_key: "{{_bas_apiKey_result.resources[0].data.apikey | b64decode }}"
    bas_endpoint_url: "https://{{_bas_endpoint.resources[0].spec.host}}"
    bas_tls_crt: "{{_bas_certificates_result.resources[0].data['tls.crt'] | b64decode | regex_findall('(-----BEGIN .+?-----(?s).+?-----END .+?-----)', multiline=True, ignorecase=True)  }}"

# 2. Write out the config to the local filesystem
# -----------------------------------------------------------------------------
- name: Copy BASCfg to filesytem
  ansible.builtin.template:
    src: bascfg.yml.j2
    dest: "{{ mas_config_dir }}/bas-{{ bas_namespace }}.yml"

```
