### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#82]
... or sort out billing in Travis, either works.

FWIW .. this is the starter I wrote a while back / completely untested but might be helpful as a starting point:

```
name: Migrated Travis CI Build

# Do a SIMPLE migration of the travis build, worry about taking advantage of other features of Actions after we get it basically working first
# See if we can get it working on one branch first
on:
  push:
    branches: [ actionstest ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Most scipts will probably fail because $GITHUB_WORKSPACE / $TRAVIS_BUILD_DIR envs are different, etc
    steps:
    - uses: actions/checkout@v2
    - name: Make scripts executable
      run: chmod u+x $TRAVIS_BUILD_DIR/build/bin/*.sh
    
    - name: Run initbuild
      run: $GITHUB_WORKSPACE/build/bin/initbuild.sh
    
    - name: Install Python requirements to build the pages documentation website
      run: python -m pip install -q ansible==2.10.3 mkdocs yamllint
      
    - name: Validate that the ansible collection lints successfully
      run: yamllint -c yamllint.yaml ibm/mas_devops
    
    - name: Validate that the mkdocs site builds successfully
      run: mkdocs build --verbose --clean --strict

    - name: Build the Ansible collection
      run: $GITHUB_WORKSPACE/build/bin/build-collection.sh
    
    - name:  Install the Ansible collection in the container image
      run: cp $GITHUB_WORKSPACE/ibm/mas_devops/ibm-mas_devops-$(cat $GITHUB_WORKSPACE/.version).tar.gz $GITHUB_WORKSPACE/image/ansible-devops/ibm-mas_devops.tar.gz

    - name: Build the docker image
      run: $GITHUB_WORKSPACE/build/bin/docker-build.sh -n ibmmas -i ansible-devops
      
    - name: Push the docker image
      run: $GITHUB_WORKSPACE/build/bin/docker-push.sh
      
    - name: Build the tekton clustertasks
      run: $TRAVIS_BUILD_DIR/pipelines/bin/build-pipelines.sh

# TODOs
# Publish a GitHub release with the ansible collection tgz as an assset
# - $TRAVIS_BUILD_DIR/build/bin/git-release.sh $TRAVIS_BUILD_DIR/ibm/mas_devops/ibm-mas_devops-$(cat $TRAVIS_BUILD_DIR/.version).tar.gz $TRAVIS_BUILD_DIR/pipelines/ibm-mas_devops-clustertasks-$(cat $TRAVIS_BUILD_DIR/.version).tar.gz

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_url: github.com
#  github_token: $GITHUB_TOKEN
#  verbose: true
#  local_dir: site
#  target_branch: gh-pages
#  on:
#    branch: master
```
