### ISSUE TITLE
db2_backup role fail with error: "CTGSK3036W The output file "/mnt/blumeta0/db2/keystore/master_key_label.kdb" already exists."

### ISSUE THREAD

**Issue by mattlrx** [ibm-mas/ansible-devops#928]
executing db2\_backup role fails because the file master\_key\_label.kdb already existed in /mnt/blumeta0/db2/keystore/

the error was:

```
TASK [ibm.mas_devops.db2_backup : Extract Master Key Label from keystore.p12] **********************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc exec -it -n db2u c-mlmax-db2u-0 -- su -lc \"gsk8capicmd_64 -secretkey -extract -db '/mnt/blumeta0/db2/keystore/keystore.p12' -stashed -label 'DB2_SYSGEN_db2inst1_BLUDB_2023-07-03-08.45.30_8403CB5A' -format ascii -target '/mnt/blumeta0/db2/keystore/master_key_label.kdb'\" db2inst1\n", "delta": "0:00:02.635918", "end": "2023-07-27 16:50:28.673852", "msg": "non-zero return code", "rc": 233, "start": "2023-07-27 16:50:26.037934", "stderr": "Defaulted container \"db2u\" out of: db2u, init-labels (init), init-kernel (init)\nUnable to use a TTY - input is not a terminal or the right kind of file\ncommand terminated with exit code 233", "stderr_lines": ["Defaulted container \"db2u\" out of: db2u, init-labels (init), init-kernel (init)", "Unable to use a TTY - input is not a terminal or the right kind of file", "command terminated with exit code 233"], "stdout": "CTGSK3036W The output file \"/mnt/blumeta0/db2/keystore/master_key_label.kdb\" already exists.", "stdout_lines": ["CTGSK3036W The output file \"/mnt/blumeta0/db2/keystore/master_key_label.kdb\" already exists."]}
```

to workaround this issue, I renamed the existing file:

cd /mnt/blumeta0/db2/keystore/

mv master\_key\_label.kdb master\_key\_label.kdb\_bkp

then rerun the playbook

for information, the playbook is:

```
- hosts: "localhost"
  any_errors_fatal: true
  vars:
    db2_namespace: "db2u"
    db2_dbname: "BLUDB"
    db2_backup_dir: "/home/matthieu/db2backup"
    db2_backup_instance_name: "mlmax"

  roles:
    - ibm.mas_devops.db2_backup
```
