### ISSUE TITLE
Cipher compatibility issue with default IngressController configuration in FIPS mode

### ISSUE THREAD

**Issue by terenceq** [ibm-mas/ansible-devops#934]
## No cipher suite in common with Semeru runtime and default IngressController configuration

This problem can be seen when a Java client (for example a connection from the Manage all or mea containers) attempts a connection to the `auth` route. An example is a connection from a Java client using IBM Semeru to the URL:

```
https://<auth route>/oidc/endpoint/MaximoAppSuite/token"
```

The [default tlsSecurityPolicy](https://docs.openshift.com/container-platform/4.12/security/tls-security-profiles.html#tls-profiles-ingress-configuring_tls-security-profiles) that is configured for the `IngressController` does not contain a cipher in common with IBM Java Semeru when running in FIPS mode. A proposed solution is to configure the `tlsSecurityProfile` in a similar fashion as what is done for the  `APIServer`. For example:

```yaml
 tlsSecurityProfile:
   custom:
     ciphers:
       - TLS_AES_128_GCM_SHA256
       - TLS_AES_256_GCM_SHA384
       - TLS_CHACHA20_POLY1305_SHA256
       - ECDHE-ECDSA-AES128-GCM-SHA256
       - ECDHE-RSA-AES128-GCM-SHA256
       - ECDHE-ECDSA-AES256-GCM-SHA384
       - ECDHE-RSA-AES256-GCM-SHA384
       - ECDHE-ECDSA-CHACHA20-POLY1305
       - ECDHE-RSA-CHACHA20-POLY1305
       - DHE-RSA-AES128-GCM-SHA256
       - DHE-RSA-AES256-GCM-SHA384
       - ECDHE-RSA-AES128-SHA256
       - ECDHE-RSA-AES128-SHA
       - ECDHE-RSA-AES256-SHA
     minTLSVersion: VersionTLS12
   type: Custom
```

The above configuration should be added to the `IngressController` resource (usually named default)

An interesting observation is that out of the box on Fyre when FIPS was enabled the IngressController did not seem to be enforcing the default profile of `Intermediate`. However, as soon as the `Intermediate` policy was set Semeru clients running in FIPS mode could no longer connect to the auth route.

Again for reference see the docs here:

https://docs.openshift.com/container-platform/4.12/security/tls-security-profiles.html#tls-profiles-ingress-configuring_tls-security-profiles
