### ISSUE TITLE
common_services fails to install

### ISSUE THREAD

**Issue by nerdingitout** [ibm-mas/ansible-devops#995]
Hi!
This is based on multiple attempts at installing common_services using the `ibm.mas_devops.common_services` role.
The cluster is Red Hat OpenShift 4.12 on IBM Cloud Satellite.
I'm using the default configurations for `ibm_catalogs` and `common_services`
I tried it on different versions and eventually upgraded to `17.0.0` but still got the same issue.

I see the following logs in `ibm-common-service-operator` pod:
```
I0905 12:51:21.679791 1 request.go:668] Waited for 1.005955224s due to client-side throttling, not priority and fairness, request: GET:https://172.21.0.1:443/apis/operators.coreos.com/v1alpha2?timeout=32s
E0905 12:51:25.858779 1 init.go:1697] Configmap ibm-common-services/ibm-cpp-config is required
E0905 12:51:25.858813 1 main.go:133] Cluster type specificed in the ibm-cpp-config isn't correct
```
The operator remains in `installing` state or turns to `failed` when I stop the automation
![Screenshot 2023-09-05 at 4 21 36 PM](https://github.com/ibm-mas/ansible-devops/assets/36239840/1d0cc441-6f1a-456a-a93a-5ad0b9390007)

and I see the following events in `ibm-common-services` namespace
![Screenshot 2023-09-05 at 4 21 54 PM](https://github.com/ibm-mas/ansible-devops/assets/36239840/9076b42e-bc6f-4b97-ad4c-5c2dde5d14b6)

**Comment by andrercm** [comment]
hello @nerdingitout 

did some research about this issue and it seems there should be a config map named `ibm-cpp-config` in the `ibm-common-services` namespace when you install IBM Common Services. 

It seems for whatever reason in your case it was not created? 

One way to check is to run the following command:

```
oc get cm ibm-cpp-config -n ibm-common-services -o yaml
```

The config map should be similar to the following (it should list all the storage classes available in your cluster):

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: ibm-cpp-config
  namespace: ibm-common-services
  labels:
    ibm-cpp-config/ibm-common-services: secretsharekey
    ibmcpcs.ibm.com/managed-by: secretshare
    manage-by-secretshare: 'true'
data:
  storageclass.default: default
  storageclass.list: >-
    default,ibmc-block-bronze,ibmc-block-custom,ibmc-block-gold,ibmc-block-retain-bronze,ibmc-block-retain-custom,ibmc-block-retain-gold,ibmc-block-retain-silver,ibmc-block-silver,ibmc-file-bronze,ibmc-file-bronze-gid,ibmc-file-custom,ibmc-file-gold,ibmc-file-gold-gid,ibmc-file-retain-bronze,ibmc-file-retain-custom,ibmc-file-retain-gold,ibmc-file-retain-silver,ibmc-file-silver,ibmc-file-silver-gid
```

Also can you ensure you do have storage classes available in your cluster? I know that IBM Cloud classic clusters already comes with default storage classes configured, but I am not sure about IBM Cloud Satellite cluster types.

**Comment by andrercm** [comment]
Closing as no response for a week.

**Comment by rhocheck** [comment]
This is still an issue. The config map is not create on OCP 4.12 on IBm Cloud Sallite. I need to create it myself

```
apiVersion: v1
data:
  storageclass.default: sat-ocs-cephfs-gold
  storageclass.list: sat-ocs-cephfs-gold,sat-ocs-cephrbd-gold,sat-ocs-cephrgw-gold
kind: ConfigMap
metadata:
  name: ibm-cpp-config
  namespace: ibm-common-services
```
